production:
  facebook:
    key: ***REMOVED***
    secret: ***REMOVED***
development:
  facebook:
    key: ***REMOVED***
    secret: ***REMOVED***
test:
  facebook:
    key: ***REMOVED***
    secret: ***REMOVED***