login: &login
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password: 
  host: localhost

development:
  <<: *login
  database: kidpins_development
  
test:
  <<: *login
  database: pins_test
  
staging:
  <<: *login
  database: pins_staging
  
production:
  <<: *login
  database: pins